name: Build&Run server

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ github.repository_owner }}/sigmabot

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  run:
    name: Pull image and Run on server
    needs: build
    runs-on: ubuntu-latest
    environment: nstu_abitur
    steps:
      - name: Pull Docker image locally
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: docker pull ${{ github.repository_owner }}/sigmabot:main
      - name: Stop existing Docker containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            if [ ! "$(docker ps -aq)" = '' ]; 
            then 
              docker rm $(docker kill $(docker ps -aq))
            fi
      - name: Run fresh Docker image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: docker run -itd --restart unless-stopped
                  -e API_ID=${{ secrets.API_ID }}
                  -e API_HASH=${{ secrets.API_HASH }}
                  -e BOT_TOKEN=${{ secrets.BOT_TOKEN }}
                  -e MONGO_URL=${{ secrets.MONGO_URL }}
                  -e REF_PAYMENT=${{ secrets.REF_PAYMENT }}
                  -e SUB_CHANNELS=${{ secrets.SUB_CHANNELS }}
                  ${{ github.repository_owner }}/sigmabot:main
